name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: Enter the name of github team

      maintainer:
        type: string
        description: Enter the name of github team maintainer

# jobs:
#   greet:
#     runs-on: ubuntu-latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8    
    # steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirement.txt      
      
    - name: Run Python script with inputs
      run: |
        python create_team_add_maintanier.py "${{ github.event.inputs.name }}" "${{ github.event.inputs.maintainer }}"
