name: Interactive Workflow
on:
  workflow_dispatch:
    inputs:
      input1:
        description: 'Input 1 description'
        required: true
      input2:
        description: 'Input 2 description'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Display Inputs
        run: |
          echo "Input 1: ${{ github.event.inputs.input1 }}"
          echo "Input 2: ${{ github.event.inputs.input2 }}"
